<?php

return array (
  'APP_SECRET' => NULL,
  'DATABASE_URL' => NULL,
  'MAILER_URL' => NULL,
  'MERCURE_JWT_SECRET' => NULL,
  'OAUTH_GITHUB_CLIENT_ID' => NULL,
  'OAUTH_GITHUB_CLIENT_SECRET' => NULL,
  'OAUTH_GOOGLE_CLIENT_ID' => NULL,
  'OAUTH_GOOGLE_CLIENT_SECRET' => NULL,
  'OAUTH_MICROSOFT_CLIENT_ID' => NULL,
  'OAUTH_MICROSOFT_CLIENT_SECRET' => NULL,
  'OAUTH_OKTA_CLIENT_ID' => NULL,
  'OAUTH_OKTA_CLIENT_SECRET' => NULL,
);
