framework:
    secret: '%env(APP_SECRET)%'
#    csrf_protection: true
#    templating:
#        engines: ['twig', 'php']
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
#        handler_id: ~
#        cookie_secure: auto
#        cookie_samesite: laxframework:
        handler_id: 'session.handler.native_file'
#        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true
