security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        user:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            logout:
                path: app_logout
            form_login:
                provider: user
                login_path: app_login
                check_path: app_login
                username_parameter: email
                password_parameter: password
                post_only: true
                use_referer: true
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
                    - App\Security\GoogleAuthenticator
                    - App\Security\GitHubAuthenticator
                    - App\Security\MicrosoftAuthenticator
                    - App\Security\OktaAuthenticator
                    - App\Security\GuestAuthenticator
                entry_point: App\Security\LoginFormAuthenticator

#            logout:
#                path: app_logout
                # where to redirect after logout
                # target: app_any_route

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true
    encoders:
        App\Entity\User: sha512

    role_hierarchy:
        ROLE_USER:        ROLE_GUEST
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/forgot-password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reset-password-request, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reset-password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/board/invitation, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET]  }
        - { path: ^/connect/google, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect/google/check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect/github, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect/github/check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect/microsoft, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect/microsoft/check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect/okta, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect/okta/check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin, roles: ROLE_ADMIN }
#        - { path: ^/profile, roles: ROLE_USER }
#        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
