version: '3'
services:

  apache:
    build: .docker/apache
    container_name: retro_board_apache
#    ports:
#      - 8185:80
    volumes:
      - .docker/apache/config/vhosts:/etc/apache2/sites-enabled
      - .:/var/www/retro_board
    depends_on:
      - php
    links:
      - php
#    network_mode: host
    networks:
      retro_board_net:
        ipv4_address: 172.0.12.1

  mysql:
    image: mysql
    restart: always
    user:
      1000:1000
    container_name: retro_board_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=XQW16asZ

    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - .docker/data/db:/var/lib/mysql
      - .:/application
#    network_mode: host
    networks:
      retro_board_net:
        ipv4_address: 172.0.12.2

#  adminer:
#    image: adminer
#    container_name: retro_board_adminer
#    restart: on-failure
#    ports:
#      - '8080:8080'
#    network_mode: host
#    networks:
#      - retro_board_net

  php:
    build:
      context: .docker/php
      dockerfile: Dockerfile
      args:
        - HOST_IP=172.0.12.1
    container_name: retro_board_php
    volumes:
      - .:/var/www/retro_board
    environment:
      - MYSQL_ROOT_PASSWORD=root
#    environment:
#      - maildev_host=retro_board_maildev
    depends_on:
#      - maildev
      - mysql
    links:
      - mysql
#    network_mode: host
    networks:
      retro_board_net:
        ipv4_address: 172.0.12.3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: retro_board_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
#    ports:
#      - 8181:80
    links:
      - mysql
#    network_mode: host
    networks:
      retro_board_net:
        ipv4_address: 172.0.12.4

#  maildev:
#    image: djfarrelly/maildev
#    container_name: retro_board_maildev
#    ports:
#      - 8001:80
#    network_mode: host
#    networks:
#      - retro_board_net

networks:
  retro_board_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.0.12.0/16

volumes:
  data:
    driver: local